function createfigure(X1, Y1, X2, X3, X4, X5, X6, X7, X8, X9, X10)
%CREATEFIGURE(X1, Y1, X2, X3, X4, X5, X6, X7, X8, X9, X10)
%  X1:  scatter x
%  Y1:  scatter y
%  X2:  scatter x
%  X3:  scatter x
%  X4:  scatter x
%  X5:  scatter x
%  X6:  scatter x
%  X7:  scatter x
%  X8:  scatter x
%  X9:  scatter x
%  X10:  scatter x

%  Auto-generated by MATLAB on 13-Dec-2018 16:04:11

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create scatter
scatter(X1,Y1,'DisplayName','A2212','MarkerFaceColor','flat',...
    'MarkerEdgeColor','none');

% Create scatter
scatter(X2,Y1,'DisplayName','A0561','MarkerFaceColor','flat',...
    'MarkerEdgeColor','none');

% Create scatter
scatter(X3,Y1,'DisplayName','A1799','MarkerFaceColor','flat',...
    'MarkerEdgeColor','none');

% Create scatter
scatter(X4,Y1,'DisplayName','A0490','MarkerFaceColor','flat',...
    'MarkerEdgeColor','none');

% Create scatter
scatter(X5,Y1,'DisplayName','A0324','MarkerFaceColor','flat',...
    'MarkerEdgeColor','none');

% Create scatter
scatter(X6,Y1,'DisplayName','A2518','MarkerFaceColor','flat',...
    'MarkerEdgeColor','none');

% Create scatter
scatter(X7,Y1,'DisplayName','A1800','MarkerFaceColor','flat',...
    'MarkerEdgeColor','none');

% Create scatter
scatter(X8,Y1,'DisplayName','A1801','MarkerFaceColor','flat',...
    'MarkerEdgeColor','none');

% Create scatter
scatter(X9,Y1,'DisplayName','A2411','MarkerFaceColor','flat',...
    'MarkerEdgeColor','none');

% Create scatter
scatter(X10,Y1,'DisplayName','A1037','MarkerFaceColor','flat',...
    'MarkerEdgeColor','none');

% Set the remaining axes properties
set(axes1,'XTick',[0 1 2 3 4 5 6]);
% Create legend
legend(axes1,'show');

